### ISSUE TITLE
UGRID, FVCOM, unknown_1d mesh, compliance problem?

### ISSUE THREAD

**Issue by nbrinks** [pyoceans/gridgeo#50]
I am trying to retrieve the `triang` from a NetCDF file. (https://noaa-ofs-pds.s3.amazonaws.com/leofs.20210114/nos.leofs.fields.f000.20210114.t00z.nc) but whenever I try to open the file the mesh that is generated is `unknown_1d`. AFAIK this NetCDF file is an unstructured grid following FVCOM. Is this some sort of compliance issue with the file? Am I doing something wrong? Any help is appreciated. Thanks!

See my example notebook at https://gist.github.com/nbrinks/004d0c96e80619815dcc0a27d0ee6b18

**Comment by ocefpaf** [comment]
> Is this some sort of compliance issue with the file? 

Yep. You did nothing wrong, the data provider needs to add more metadata to make this a ugrid compliant dataset. See both checks in the last cell of the notebook below:

https://nbviewer.jupyter.org/gist/ocefpaf/c5e6027b26bd52c163bf1819c1d1ab65

Closing this b/c it is not a problem with gridgeo.
